_wandb:
    value:
        cli_version: 0.22.1
        e:
            52uq0z7b03vs2crwbhvx2tyu40cxex13:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269424332800"
                        used: "156951150592"
                email: jhaadarsh350@gmail.com
                executable: /home/adarsh/miniconda3/envs/pevslam/bin/python
                git:
                    commit: f27869895d7c565b91d445044db8e0bc4dda5d21
                    remote: git@github.com:jha-adarsh18/PEVSLAM.git
                host: adarsh-ZenBook
                memory:
                    total: "16451108864"
                os: Linux-6.14.0-32-generic-x86_64-with-glibc2.39
                program: -m scripts.triplet_train
                python: CPython 3.12.11
                root: /home/adarsh/PEVSLAM
                startedAt: "2025-10-06T12:00:17.181095Z"
                writerId: 52uq0z7b03vs2crwbhvx2tyu40cxex13
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.12.11
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
architecture:
    value: PEVSLAM
batch_size:
    value: 8
epochs:
    value: 50
learning_rate:
    value: 0.001
train_samples:
    value: 901790
val_samples:
    value: 100199
