_wandb:
    value:
        cli_version: 0.22.1
        e:
            dbcvvvyh5wt1ajjyafrh7uk2ew7okwcy:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269424332800"
                        used: "160102604800"
                email: jhaadarsh350@gmail.com
                executable: /home/adarsh/miniconda3/envs/pevslam/bin/python
                git:
                    commit: 590eee04eb026995f83d018a2dd337eb8756e9ea
                    remote: git@github.com:jha-adarsh18/PEVSLAM.git
                host: adarsh-ZenBook
                memory:
                    total: "16451129344"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: -m scripts.triplet_train
                python: CPython 3.12.11
                root: /home/adarsh/PEVSLAM
                startedAt: "2025-10-10T14:13:52.221983Z"
                writerId: dbcvvvyh5wt1ajjyafrh7uk2ew7okwcy
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.12.11
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
architecture:
    value: PEVSLAM
batch_size:
    value: 8
epochs:
    value: 50
learning_rate:
    value: 0.001
train_samples:
    value: 901790
val_samples:
    value: 100199
