corridor_dolly:
    K_left: [[327.32749, 0.0, 304.97749],
             [0.0, 327.46184, 235.37621],
             [0.0, 0.0, 1.0]]
    K_right: [[327.48497, 0.0, 318.53477],
              [0.0, 327.55395, 230.96356],
              [0.0, 0.0, 1.0]]
    baseline: 0.1717

indoor_flying1:
  K_left: [[226.3801852, 0.0, 173.6470808],
           [0.0, 226.1500295, 133.7327149],
           [0.0, 0.0, 1.0]]
  K_right: [[226.01814185, 0.0, 174.54335767],
            [0.0, 225.78694343, 124.21627573],
            [0.0, 0.0, 1.0]]
  baseline: 0.09988
    