corridor_dolly:
    K_left: [[327.32749, 0.0, 304.97749],
             [0.0, 327.46184, 235.37621],
             [0.0, 0.0, 1.0]]
    K_right: [[327.48497, 0.0, 318.53477],
              [0.0, 327.55395, 230.96356],
              [0.0, 0.0, 1.0]]
    baseline: 0.1717

    